// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PJATK_APBD_Cw7_s33974.Infrastructure;

#nullable disable

namespace PJATK_APBD_Cw7_s33974.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517164229_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PJATK_APBD_Cw7_s33974.Models.ComponentManufacturers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "AMD",
                            FoundationDate = new DateOnly(1969, 5, 1),
                            FullName = "Advanced Micro Devices"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "NV",
                            FoundationDate = new DateOnly(1993, 4, 5),
                            FullName = "NVIDIA Corporation"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "COR",
                            FoundationDate = new DateOnly(1994, 1, 1),
                            FullName = "Corsair Gaming Inc."
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33974.Models.ComponentTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Processor"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Card"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Memory"
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33974.Models.Components", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentsManufacturersId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentsTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentsManufacturersId");

                    b.HasIndex("ComponentsTypeId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "CPU0000001",
                            ComponentsManufacturersId = 1,
                            ComponentsTypeId = 1,
                            Description = "8-core gaming processor",
                            Name = "Ryzen 7 7800X3D"
                        },
                        new
                        {
                            Code = "GPU0000001",
                            ComponentsManufacturersId = 2,
                            ComponentsTypeId = 2,
                            Description = "High-end gaming graphics card",
                            Name = "RTX 4080 Super"
                        },
                        new
                        {
                            Code = "RAM0000001",
                            ComponentsManufacturersId = 3,
                            ComponentsTypeId = 3,
                            Description = "DDR5 RAM module 16GB",
                            Name = "Corsair Vengeance DDR5 16GB"
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33974.Models.PCComponents", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PCId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents");

                    b.HasData(
                        new
                        {
                            PCId = 1,
                            ComponentCode = "CPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "GPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "RAM0000001",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "RAM0000001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "RAM0000001",
                            Amount = 4
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "CPU0000001",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "GPU0000001",
                            Amount = 2
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33974.Models.PCs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("PCs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming Beast X",
                            Stock = 5,
                            Warranty = 36,
                            Weight = 12.5m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office Mini Pro",
                            Stock = 12,
                            Warranty = 24,
                            Weight = 4.2m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming Beast XII",
                            Stock = 1,
                            Warranty = 12,
                            Weight = 15m
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33974.Models.Components", b =>
                {
                    b.HasOne("PJATK_APBD_Cw7_s33974.Models.ComponentManufacturers", "ComponentManufacturers")
                        .WithMany("Components")
                        .HasForeignKey("ComponentsManufacturersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PJATK_APBD_Cw7_s33974.Models.ComponentTypes", "ComponentTypes")
                        .WithMany("Components")
                        .HasForeignKey("ComponentsTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturers");

                    b.Navigation("ComponentTypes");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33974.Models.PCComponents", b =>
                {
                    b.HasOne("PJATK_APBD_Cw7_s33974.Models.Components", "Component")
                        .WithMany("PCComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PJATK_APBD_Cw7_s33974.Models.PCs", "PC")
                        .WithMany("PCComponents")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("PC");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33974.Models.ComponentManufacturers", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33974.Models.ComponentTypes", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33974.Models.Components", b =>
                {
                    b.Navigation("PCComponents");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33974.Models.PCs", b =>
                {
                    b.Navigation("PCComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
